Deliverable 3: Create a Travel Itinerary Map

In [22]:
import pandas as pd
import requests
import gmaps

from config import g_key
gmaps.configure(api_key=g_key)

Read the WeatherPy_vacation.csv into a DataFrame.

In [29]:
vacation_df = pd.read_csv("weatherpy_vacation.csv")
vacation_df

City_ID          City Country  Max Temp Current Description      Lat  \
0          2    Butaritari      KI     80.51          light rain   3.0707   
1          8         Kapaa      US     74.12    scattered clouds  22.0752   
2         15        Atuona      PF     78.58          light rain  -9.8000   
3         16    Sao Mateus      BR     84.42           clear sky -18.7161   
4         17   Baikunthpur      IN     89.08    scattered clouds  23.2500   
..       ...           ...     ...       ...                 ...      ...   
229      649        Ranong      TH     80.11     overcast clouds   9.9658   
230      650     Lalawigan      PH     79.21    scattered clouds  11.5892   
231      655       Cozumel      MX     86.95       broken clouds  20.5083   
232      658      Celestun      MX     86.56           clear sky  20.8667   
233      664  Aguas Verdes      PE     86.27    scattered clouds  -3.4814   

          Lng                            Hotel Name  
0    172.7902                    Isles Sunset Lodge  
1   -159.3190   Sheraton Kauai Coconut Beach Resort  
2   -139.0333                           Villa Enata  
3    -39.8589                       Hotel Rio Norte  
4     82.5500                 Hotel Shree Annapurna  
..        ...                                   ...  
229   98.6348                  Tinidee Hotel@Ranong  
230  125.4697                       Palms Apartment  
231  -86.9458  Cozumel Palace® All Inclusive Resort  
232  -90.4000                          Posada Lilia  
233  -80.2450                     Sol Del Sur Hotel  

[234 rows x 8 columns]

Using the template add the city name, the country code, the weather description and maximum temperature for the city.

In [79]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

Get the data from each row and add it to the formatting template and store the data in a list.

In [80]:
hotel_info = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]

Get the latitude and longitude from each row and store in a new DataFrame.

In [81]:
locations = vacation_df[["Lat", "Lng"]]

In [82]:
locations

Lat       Lng
0     3.0707  172.7902
1    22.0752 -159.3190
2    -9.8000 -139.0333
3   -18.7161  -39.8589
4    23.2500   82.5500
..       ...       ...
229   9.9658   98.6348
230  11.5892  125.4697
231  20.5083  -86.9458
232  20.8667  -90.4000
233  -3.4814  -80.2450

[234 rows x 2 columns]

Add a marker layer for each city to the map.

Display the figure.

In [83]:
locations = vacation_df[["Lat", "Lng"]]
max_temp = vacation_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,
             dissipating=False, max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

fig

Figure(layout=FigureLayout(height='420px'))

From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities. 

Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 

Hint: The starting and ending city should be the same city.

In [30]:
vacation_start = vacation_df.loc[vacation_df["City"] == "Sao Mateus"]
vacation_end = vacation_df.loc[vacation_df["City"] == "Sao Mateus"]
vacation_stop1 = vacation_df.loc[vacation_df["City"] == "Vila Velha"]
vacation_stop2 = vacation_df.loc[vacation_df["City"] == "Sao Joao Da Barra"] 
vacation_stop3 = vacation_df.loc[vacation_df["City"] == "Arraial Do Cabo"] 

Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.

In [31]:
import numpy

In [59]:
start = vacation_start[["Lat", "Lng"]].to_numpy()
end = vacation_end[["Lat", "Lng"]].to_numpy()
stop1 = vacation_stop1[["Lat", "Lng"]].to_numpy()
stop2 = vacation_stop2[["Lat", "Lng"]].to_numpy()
stop3 = vacation_stop3[["Lat", "Lng"]].to_numpy()

In [45]:
start

array([[-18.7161, -39.8589]])

In [46]:
stop1

array([[-20.3297, -40.2925]])

In [47]:
stop2

array([[-21.6403, -41.0511]])

In [48]:
stop3

array([[-22.9661, -42.0278]])

In [49]:
end

array([[-18.7161, -39.8589]])

Create a direction layer map using the start and end latitude-longitude pairs, and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".

In [66]:
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
start = (-18.7161, -39.8589)
end = (-18.7161, -39.8589)
waypoints = [(-20.3297, -40.2925), (-21.6403, -41.0511), (-22.9661, -42.0278) ]
directions = gmaps.directions_layer(start, end, waypoints=waypoints, travel_mode='DRIVING')

fig.add_layer(directions)

fig

Figure(layout=FigureLayout(height='420px'))

Create a marker layer map between the four cities.

Combine the four city DataFrames into one DataFrame using the concat() function.

In [68]:
itinerary_df = pd.concat([vacation_start, vacation_stop1, vacation_stop2, vacation_stop3, vacation_end],ignore_index=True)
itinerary_df

City_ID               City Country  Max Temp Current Description      Lat  \
0       16         Sao Mateus      BR     84.42           clear sky -18.7161   
1       21         Vila Velha      BR     87.75          few clouds -20.3297   
2      522  Sao Joao Da Barra      BR     87.89          few clouds -21.6403   
3      311    Arraial Do Cabo      BR     76.96       broken clouds -22.9661   
4       16         Sao Mateus      BR     84.42           clear sky -18.7161   

       Lng               Hotel Name  
0 -39.8589          Hotel Rio Norte  
1 -40.2925     Hotel Vitória Palace  
2 -41.0511  Pousada Porto De Canoas  
3 -42.0278      Pousada Porto Praia  
4 -39.8589          Hotel Rio Norte

Using the template add city name, the country code, the weather description and maximum temperature for the city. 

In [69]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

Get the data from each row and add it to the formatting template and store the data in a list.

In [70]:
hotel_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]

Get the latitude and longitude from each row and store in a new DataFrame.

In [71]:
locations = itinerary_df[["Lat", "Lng"]]

Add a marker layer for each city to the map.

Display the figure

In [74]:
locations = itinerary_df[["Lat", "Lng"]]
max_temp = itinerary_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,
             dissipating=False, max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)


fig

Figure(layout=FigureLayout(height='420px'))